language: node_js
node_js: 6
before_install:
  - git checkout -
  - git config --global push.default simple
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GITHUB_API_KEY}:@github.com" > .git/credentials
after_success:
  - git add . && git commit -m "Update test files"
deploy:
  - provider: script
    skip_cleanup: true
    script: npm version minor -m "Create new version: %s [skip ci]"
    on:
     branch: master
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_API_KEY
    on:
      branch: release
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_API_KEY
    on:
      branch: release
