language: node_js
node_js: 6
before_install:
  - git checkout -
  - git config --global push.default simple
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GITHUB_API_KEY}:@github.com" > .git/credentials
deploy:
  - provider: script
    script: /bin/sh tools/version.sh minor
    on:
      branch: master
  - provider: pages
    github_token: $GITHUB_API_KEY
    on:
      branch: release
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_API_KEY
    on:
      branch: release

